name: 'Tizen CI/CD'
description: 'Run Tizen commands in github actions. This builds and packages tizen applications.'
inputs:
  command:
    description: 'Tizen Application Type: (web|native)'
    required: true
  app-directory:
    description: 'Git location of Tizen application'
    required: true
    default: 'tizen'
  cert-pw:
    description: 'Password used for the cert'
    required: true
  dist-cert:
    description: 'location to the distribution certification from the github workspace'
    required: true
  dist-cert-pw:
    description: 'Password used for the distribution cert'
    required: true
  cert-name:
    description: 'Generates a cert file with a specific name'
    required: false
    default: 'devcert'
  zip:
    description: 'Zip Results for release build'
    required: false
    default: 'false'
  type:
    description: 'Type field for pkginfo.xml in zip file'
    default: 'Kiosk'
    required: false
  exclusions:
    description: 'web build exclusions'
    required: false
    default: '*.zip'
  version:
    description: 'Set the release version - if not this will be pulled from the config file'
    required: false
outputs:
  file:
    description: 'File location'
  zip:
    description: 'Zip location'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/vipero07/docker-tizen-ci-cd:latest'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.app-directory }}
    - ${{ inputs.cert-pw }}
    - ${{ inputs.dist-cert }}
    - ${{ inputs.dist-cert-pw }}
    - ${{ inputs.cert-name }}
    - ${{ inputs.exclusions }}
    - ${{ inputs.zip }}
    - ${{ inputs.type }}
    - ${{ inputs.version }}